import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  stages: [
    { duration: '15s', target: 50 },  
    { duration: '30s', target: 50 },  
    { duration: '15s', target: 200 }, 
    { duration: '30s', target: 200 }, 
    { duration: '15s', target: 500 }, 
    { duration: '10s', target: 0 },   
  ],
};

const BASE_URL = 'https://taskus-api-docker-d4g7a9adb3d0e7bv.francecentral-01.azurewebsites.net'; 

const TARGET_TASK_GROUP_ID = '4b2e1c30-c2b6-4971-8d04-413e49954aa8';

// 1. log in as the Admin test user
export function setup() {
  const loginPayload = JSON.stringify({
    email: 'admin@testorg.com',
    password: 'testadminpassword',
  });

  const loginRes = http.post(`${BASE_URL}/user/login`, loginPayload, {
    headers: { 'Content-Type': 'application/json' },
  });
  
  return { 
    token: loginRes.json('authToken'),
    userId: loginRes.json('userInfo.id')
  }; 
}

// 2. admin Read & Write Cycle
export default function (data) {
  const headers = {
    'Authorization': `Bearer ${data.token}`,
    'Content-Type': 'application/json',
  };

  // --- ACTION 1: read (GET user) ---
  const userInfoRes = http.get(`${BASE_URL}/user/${data.userId}`, { headers });
  check(userInfoRes, { 'Fetched user': (r) => r.status === 200 });

  // --- ACTION 2: read (GET tasks by user) ---
  const getTasksRes = http.get(`${BASE_URL}/task/byUser/${data.userId}`, { headers });
  check(getTasksRes, { 'Fetched task list': (r) => r.status === 200 });

  // --- ACTION 3: write (POST create task) ---
  const taskPayload = JSON.stringify({
    title: `Ghost Task ${Math.floor(Math.random() * 100000)}`,
    description: 'Generated by k6 stress test',
    responsibleId: data.userId,
    taskGroupId: TARGET_TASK_GROUP_ID
  });

  const createRes = http.post(`${BASE_URL}/task`, taskPayload, { headers });
  
  check(createRes, { 'Created task': (r) => r.status === 200 || r.status === 201 });
  if (createRes.status !== 200 && createRes.status !== 201) {
    console.log(`CREATE ERROR: ${createRes.status} | Body: ${createRes.body}`);
  }
  const newTaskId = createRes.json('id'); 

  // --- ACTION 4: cleanup ---
  if (newTaskId) {
    const deleteRes = http.del(`${BASE_URL}/task/${newTaskId}`, null, { headers });
    check(deleteRes, { 'Deleted task': (r) => r.status === 200 });
    
    if (deleteRes.status !== 200) {
      console.log(`DELETE ERROR: ${deleteRes.status} | Body: ${deleteRes.body}`);
    }
  }

  sleep(1); 
}